double: "double shots"
triple: "triple shots"
skillShots: "&cYou performed {skillshot}."
notEnoughArrows: "&cYou don't have enough arrows to perform this skill."
notMetSkill: "&cYou haven't unlock Triple Shot skill."
delay: 5