name: MultiShot
version: 1.1.1
author: xX4w3s0m3Xx
main: me.ruud.multishot.MultiShot
commands:
  multishot:
    aliases:
      - ms
    description: MultiShot commands
    usage: |
      /<command> [abilityname] - Switch to certain ability.
permissions:
  multishot.skills.doubleShot:
    description: "Permits to use the multishot double mode"
  multishot.skills.tripleShot:
    description: "Permits to use the multishot triple mode"
  multishot.skills.quintupleShot:
    description: "Permits to use the multishot quintuple mode"